version: '3'
services:
  frontend:
    container_name: code-editor-app-webpack
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './:/app'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true